version: '3.8'

services:
  crawler-wechat:
    image: kingfalse/graalvm-jdk:21-ol9
    container_name: prod-entvault
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./target:/app
    restart: always
    ports:
      - "8080:8080"
    command: ["java", "-Dfile.encoding=UTF-8", "-jar", "/app/app.jar"]